export const OBTER_PROJETOS = "OBTER_PROJETOS"
export const CASDASTRAR_PROJETO = "CASDASTRAR_PROJETO"
export const ALTERAR_PROJETO = "ALTERAR_PROJETO"
export const DELETAR_PROJETO = "DELETAR_PROJETO"

export const OBTER_TAREFAS = "OBTER_TAREFAS"
export const CADASTRAR_TAREFA = "CADASTRAR_TAREFA"
export const ALTERAR_TAREFA = "ALTERAR_TAREFA"


